### ISSUE TITLE
'Something went wrong.' in dashboard of 'View details'

### ISSUE THREAD

**Issue by TechVentureBuilder** [mikecao/umami#503]
After updating from version 1.11 to 1.13, I get 'Something went wrong.' in the dashboard of the detail view.

![Screenshot from 2021-02-23 15-21-49](https://user-images.githubusercontent.com/54592111/108857559-82f83100-75eb-11eb-8ecf-51bdf2c1cd91.png)

**Comment by gnarlex** [comment]
I had the same problem after upgrading. For me it was due to the domain name containing a protocol (`http://localhost:3001` instead of just`localhost:3001`). After removing the protocl from the domain name the error was gone.

Can you share the error thrown in the web console?

**Comment by TechVentureBuilder** [comment]
`XHR GET https://... [HTTP/1.1 400 Bad Request 111ms]`
`XHR GET https://... [HTTP/1.1 400 Bad Request 75ms]`
`XHR GET https://... [HTTP/1.1 400 Bad Request 70ms]`
`XHR GET https://... [HTTP/1.1 400 Bad Request 69ms]`
`XHR GET https://... [HTTP/1.1 400 Bad Request 111ms]`
`XHR GET https://... [HTTP/1.1 400 Bad Request 164ms]`

`TypeError: t.reduce is not a function | NextJS 38 | backend.js:6:2315`

`TypeError: e.map is not a function | NextJS 37 | backend.js:6:2315`

**Comment by gnarlex** [comment]
The errors you shared lead me to suspect that your domain name in the settings is invalid. The API therefore rejects the metrics request with `400 Bad Request`. Prior to 1.13, umami allowed many actually invalid domain names to be entered by the user.

Does the domain name of the analyzed website contain a protocol or anything extra? You can check under `/settings` and if it does, you can also fix the domain name there via `Edit`. After removing all the "extra bits" it should work again as expected.

Some examples:
Valid domain names: `localhost:3000`, `example.com`, `www.foo.bar`
Invalid domain names: `http://localhost:3000`, `https://www.foo.bar`, `example.com/app`

**Comment by TechVentureBuilder** [comment]
@gnarlex Thanks, that's it!

I also track events using CSS classes.
Like this:
`<button id="subscribe-button" class="button umami--click--subscribe-button">Sign up</button>`

It still gives me 'Something went wrong.' in 'Events'.
Please see below.

![Screenshot from 2021-02-24 12-29-54](https://user-images.githubusercontent.com/54592111/108994593-49cbc980-769c-11eb-93b8-30bfe73b4fef.png)


It also doesn't give me the 'Events' in the 'realtime logs'.
It says 'No data available'.
Please see below.

I triggered an event through clicking on the 'Submit' button.

![Screenshot from 2021-02-24 12-52-04](https://user-images.githubusercontent.com/54592111/108996807-26eee480-769f-11eb-9b09-9e288fe64e44.png)

**Comment by gnarlex** [comment]
> Because it still gives me 'Something went wrong.' in 'Events'.

This bug is already tracked in issue #495 and a fix has already been merged into `dev` (see PR #496 for details)

**Comment by TechVentureBuilder** [comment]
@gnarlex I just realized, thanks!
